### ISSUE TITLE
Project Peer Review 

### ISSUE THREAD

**Issue by theMaxK** [KyleSanborn/Project-Repository#1]
Hi Kyle, 

here is my feedback to your Website:

   1.    Technical issues / bugs / suggestions: 
   1.1. The first suggestion I'd like to make is regarding your <img> tags. By looking over your code, I saw that they are missing the 'title' attribute. I think this is easy to change and just a minor issue. 
    1.2  The second suggestion is regarding the '.box' class: here I would suggest to use 'auto' for the 'width' and 'margin' in order to get it perfectly centered on every site. I really liked the box design and think it fits super well with the overall theme of your website. I think with those two small technical changes, it is going to be even better. 
    2.    Content Suggestions: 
    2.1. Regarding your content, my first suggestion would be, that you could implement a site where you talk a little bit about your favorite players, or the rooster in general. I think that would be a great addition besides your already great webpage. 
    2.2  As second suggestion, you could think about adding another page called 'Fanshop' where you could reference jerseys, hat's, etc, in order for the fans to be redirected to an official fanshop. I think that could be a fun and useful addition. 

Overall, I wanted to say that I really enjoyed clicking and browsing through your website. I liked the design and the feel of it and think you've done a great job! 

Best 
Max

**Comment by KyleSanborn** [comment]
Thank you for your feedback! I made sure to include all of the title tags I was missing, and did my best to make everything seem more centered. I also tried to clean up different parts of the theme to make it look more polished. I appreciate the thought that you put into your recommendations and have to say you made great recommendations.
