### ISSUE TITLE
Project Peer Review Hillary Yaory

### ISSUE THREAD

**Issue by hillaryyaory** [KyleSanborn/Project-Repository#2]
Two suggestions on content:
Images aren’t aligned
The images for the Stanley Cup are not of the same height/don’t line up, which makes it look a bit messy. Try to resize the image. 

Using a host of bold colors
I love your logo, navigation bar, and red fulfills the blue, and white color scheme. However, I feel as though that since you are working with royal blue and bright red, the colors are extremely bold colors. I think it’s best to make it less subtle, perhaps removing the red sides. Choosing bold colors is not a bad idea, just make sure to match the perfect lighter/subtler shades, which is a big challenge to deal with.

three technical bugs:

Cluttered homepage/history
Homepage is trying to present too much information, this causes it to become cluttered. A cluttered homepage can be overwhelming and difficult to read, making it hard for visitors to find what they’re looking for. Your homepage has a lot of small text in Arial, but I think it is useful information to have somewhere in your website. Therefore, I think you should paraphrase it so it’s less wordy/or move it to the contact/about us page, add font size, and change the font style to make it less bleak. Also I would recommend putting the words on the right side of the image instead of below the image. 

I feel that the history part has a lot of text. However, I also think that the history part is very cut down short. I would definitely add more information. Seeing if this were to happen, for the technical side, I wouldn’t want to scroll down the whole page instead I would prefer having to click buttons for more information (like a dropdown menu for information).

Use Ul and Li in sitemap
Instead of using a h1 for Sitemap, use a ul instead. This makes the list aligned and clean. Also a ul element represents an unordered list of items which is what you want anyways.

Missing title tags in images.
A lot of the images are missing title tags.

**Comment by KyleSanborn** [comment]
Thank you for your feedback! I adjusted the Stanley cup images so that they are not as cluttered anymore. I also trimmed down the content on my homepage to make it less overwhelming and incorporated a slide show above the text to make it more simple to view. I also made sure to add all of the missing title tags! I appreciate your help!
